# Generated by Django 4.1.5 on 2023-02-04 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_memberchip_product_membership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='membership',
        ),
        migrations.AddField(
            model_name='customer',
            name='membership',
            field=models.CharField(choices=[('B', 'BronZe'), ('S', 'Silver'), ('G', 'Gold')], default='B', max_length=1),
        ),
    ]
